### PR TITLE
dockerize generation of lua-tree and regenerate for 2.8

### PR DESCRIPTION
**Pull request by GGabriele**

### CODE REVIEW

**Comment by GGabriele** [comment]
@mikefero regenerating the lua-tree mostly updated some dependences and libs, except for the `lua-tree/share/lua/5.1/kong/db/schema/init.lua.orig` file which is a product of the `patch` command. Do you think we ignore/remove/keep stuff like that here?

**Comment by mikefero** [comment]
> @mikefero regenerating the lua-tree mostly updated some dependences and libs, except for the `lua-tree/share/lua/5.1/kong/db/schema/init.lua.orig` file which is a product of the `patch` command. Do you think we ignore/remove/keep stuff like that here?

All those `.orig` files should have been added if there was a mismatch in the patch file; we could use `--no-backup-if-mismatch`, but I think it would be better if we clean up the patch to ensure correctness; WDYT?

**Comment by mikefero** [comment]
> Regarding the new test we were supposed to add to check the new `referenceable`: I just realized, it's not a field but rather a field's attribute. It's not fully clear to me if in `goks` validators we can inspect that deep (I don't think so though).

Yeah we can't without changes and we can't easily inject vault entities either without some significant updates. I think though simply making a field referenceable will be sufficient in this case and just let it run though one of the existing scheama validation tests.

The `rate-limiting.lua` schema in the testdata folder can be updated to add the `referenceable` for the `redis_username` and `redis_password` for completeness:

```
{ redis_password = { type = "string", len_min = 0, referenceable = true }, },
{ redis_username = { type = "string", referenceable = true }, },
```

**Comment by GGabriele** [comment]
@mikefero this is ready for review!

**Comment by GGabriele** [comment]
@mikefero thanks! I just updated the commits now!

**Pull request merged**
